In [13]:
import sympy as sp
import numpy as np

In [3]:
P = np.array([[0.3, 0.6, 0.1],
              [0.4, 0.4, 0.2],
              [0.2, 0.3, 0.5]])

In [8]:
P2 = P@P
P2

array([[0.35, 0.45, 0.2 ],
       [0.32, 0.46, 0.22],
       [0.28, 0.39, 0.33]])

In [9]:
round(sum(P[0]))

1

In [10]:
round(sum(P[1]))

1

In [11]:
round(sum(P[2]))

1

In [17]:
λ = sp.Symbol('λ')
A = sp.Matrix([[0.3-λ, 0.6, 0.1],
              [0.4, 0.4-λ, 0.2],
              [0.2, 0.3, 0.5-λ]])

In [18]:
E = A.det()
sp.pprint(E.expand())

   3        2                
- λ  + 1.2⋅λ  - 0.15⋅λ - 0.05


In [30]:
E *= -1
sp.pprint(E.expand())

 3        2                
λ  - 1.2⋅λ  + 0.15⋅λ + 0.05


In [31]:
coeffs = sp.Poly(E, λ).all_coeffs()
coeffs

[1.00000000000000, -1.20000000000000, 0.150000000000000, 0.0500000000000000]

In [45]:
coeffs = (0.05, 0.15, -1.2, 1)

In [46]:
polyroots = np.polynomial.polynomial.polyroots(coeffs)
polyroots

array([-0.14494897,  0.34494897,  1.        ])

In [41]:
A = np.array([[1, 1, 1],
              [-0.7, 0.4, 0.2],
              [0.6, -0.6, 0.3]])

b = np.array([1, 0, 0])

In [42]:
np.linalg.solve(A, b)

array([0.32, 0.44, 0.24])