In [120]:
import numpy as np
from scipy.stats import t
import statsmodels.api as sm

In [121]:
X_1 = np.array([22, 17, 18, 15, 24, 22, 20, 17, 21, 18, 22, 20, 17, 15, 21, 15])

X_2 = np.array([180, 154, 217, 170, 103, 163, 180, 140, 92, 173, 87, 93, 210, 110, 86, 175])

X_3 = np.array([518, 475, 510, 493, 516, 476, 471, 523, 483, 542, 501, 471, 523, 538, 472, 467])

X_4 = np.array([2801, 2543, 2573, 2648, 2643, 2612, 2815, 2527, 2720, 2817, 2736, 2682, 2593, 2627, 2532, 2693])

In [122]:
len(X_1)

16

In [123]:
X = np.array([np.ones_like(X_1), X_1, X_2, X_3, X_4])
X = np.concatenate(X).reshape(5, 16)
X

array([[   1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1],
       [  22,   17,   18,   15,   24,   22,   20,   17,   21,   18,   22,
          20,   17,   15,   21,   15],
       [ 180,  154,  217,  170,  103,  163,  180,  140,   92,  173,   87,
          93,  210,  110,   86,  175],
       [ 518,  475,  510,  493,  516,  476,  471,  523,  483,  542,  501,
         471,  523,  538,  472,  467],
       [2801, 2543, 2573, 2648, 2643, 2612, 2815, 2527, 2720, 2817, 2736,
        2682, 2593, 2627, 2532, 2693]])

In [124]:
X.T

array([[   1,   22,  180,  518, 2801],
       [   1,   17,  154,  475, 2543],
       [   1,   18,  217,  510, 2573],
       [   1,   15,  170,  493, 2648],
       [   1,   24,  103,  516, 2643],
       [   1,   22,  163,  476, 2612],
       [   1,   20,  180,  471, 2815],
       [   1,   17,  140,  523, 2527],
       [   1,   21,   92,  483, 2720],
       [   1,   18,  173,  542, 2817],
       [   1,   22,   87,  501, 2736],
       [   1,   20,   93,  471, 2682],
       [   1,   17,  210,  523, 2593],
       [   1,   15,  110,  538, 2627],
       [   1,   21,   86,  472, 2532],
       [   1,   15,  175,  467, 2693]])

In [125]:
Y = np.array([452, 377, 478, 371, 397, 404, 427, 396, 399, 418, 413, 412, 423, 393, 381, 401])
Y

array([452, 377, 478, 371, 397, 404, 427, 396, 399, 418, 413, 412, 423,
       393, 381, 401])

Визначити статистичні оцінки для  параметрів лінійної множинної регресії

In [126]:
Z = np.linalg.inv(X @ X.T)
Z

array([[ 7.01790808e+01, -6.21497193e-02,  7.43218226e-04,
        -4.63962538e-02, -1.72574127e-02],
       [-6.21497193e-02,  1.08224750e-02,  2.84171274e-04,
         1.20018660e-04, -9.20125316e-05],
       [ 7.43218226e-04,  2.84171274e-04,  4.20632622e-05,
        -7.29019551e-06, -3.24807762e-06],
       [-4.63962538e-02,  1.20018660e-04, -7.29019551e-06,
         1.04864905e-04, -2.67503087e-06],
       [-1.72574127e-02, -9.20125316e-05, -3.24807762e-06,
        -2.67503087e-06,  7.82416824e-06]])

In [127]:
X_Y = X @ Y
X_Y

array([    6542,   124541,   963527,  3265275, 17415854])

In [128]:
B = Z @ X_Y
B

array([38.36248329,  4.48220738,  0.40965836,  0.22345745,  0.04292348])

In [129]:
eq_str = 'y = '

for i in range(len(B)):
    print(f'b{i} = {B[i]:.4f}')
    eq_str += f'{B[i]:.4f} '
    if i != 0:
        eq_str += f'* x_i{i} '
    if i+1 != len(B):
        eq_str += '+ '
    
print(eq_str)

b0 = 38.3625
b1 = 4.4822
b2 = 0.4097
b3 = 0.2235
b4 = 0.0429
y = 38.3625 + 4.4822 * x_i1 + 0.4097 * x_i2 + 0.2235 * x_i3 + 0.0429 * x_i4 


Побудувати довірчий інтервал

In [130]:
y = 0.99
alpha = 1 - y
print(f'alpha = {alpha:.2f}')

alpha = 0.01


In [131]:
n = X.shape[1]
n

16

In [132]:
m = X.shape[0]
m

5

In [133]:
pred_Y = B @ X
pred_Y

array([446.68918495, 392.94410176, 432.34350077, 399.06342053,
       416.88108084, 422.22724173, 427.82319903, 397.24806638,
       394.85922932, 431.94250134, 402.00215467, 386.47409856,
       428.75710135, 383.63811094, 381.87363231, 397.23337552])

In [134]:
e = Y - pred_Y
e

array([  5.31081505, -15.94410176,  45.65649923, -28.06342053,
       -19.88108084, -18.22724173,  -0.82319903,  -1.24806638,
         4.14077068, -13.94250134,  10.99784533,  25.52590144,
        -5.75710135,   9.36188906,  -0.87363231,   3.76662448])

In [135]:
S_2 = np.sum(e**2) / (n-m)
print(S_2)

454.9108291901238


In [136]:
S = np.sqrt(S_2)
print(S)

21.328638709259526


In [137]:
t_val = t.ppf(1-alpha/2, df=n-m)
print(t_val)

3.1058065155392804


In [138]:
for i in range(Y.shape[0]):
    x_0 = X.T[i].reshape(-1, 1)
    y_0 = pred_Y[i]
    
    margin = t_val*S*np.sqrt((x_0.T @ Z @ x_0)[0][0])
    
    low = y_0 - margin
    high = y_0 + margin
    
    print(f'y[{i}]: [{low:.4f}, {high:.4f}]')

y[0]: [407.9268, 485.4515]
y[1]: [361.3168, 424.5714]
y[2]: [394.0652, 470.6218]
y[3]: [368.7144, 429.4124]
y[4]: [376.7843, 456.9778]
y[5]: [386.6050, 457.8495]
y[6]: [387.1404, 468.5060]
y[7]: [362.9457, 431.5504]
y[8]: [364.9131, 424.8053]
y[9]: [389.2439, 474.6411]
y[10]: [369.5141, 434.4902]
y[11]: [355.1563, 417.7919]
y[12]: [393.6448, 463.8694]
y[13]: [336.8288, 430.4474]
y[14]: [343.5669, 420.1804]
y[15]: [356.0595, 438.4073]


In [139]:
model = sm.OLS(Y.reshape(16,1), X.T).fit()

In [140]:
predictions = model.get_prediction(X.T)
conf_int = predictions.conf_int(alpha=alpha)

In [141]:
for i, (features, intervals) in enumerate(zip(X.T, conf_int), 1):
    feature = tuple(int(val) for val in features[1:])
    interval = tuple(round(float(val), 2) for val in intervals)
    
    print(f'Вектор ознак [{i}]: {feature}')
    print(f'Довірчий інтервал [{i}]: {interval}')
    print()

Вектор ознак [1]: (1, 22, 180, 518, 2801)
Довірчий інтервал [1]: (407.93, 485.45)

Вектор ознак [2]: (1, 17, 154, 475, 2543)
Довірчий інтервал [2]: (361.32, 424.57)

Вектор ознак [3]: (1, 18, 217, 510, 2573)
Довірчий інтервал [3]: (394.07, 470.62)

Вектор ознак [4]: (1, 15, 170, 493, 2648)
Довірчий інтервал [4]: (368.71, 429.41)

Вектор ознак [5]: (1, 24, 103, 516, 2643)
Довірчий інтервал [5]: (376.78, 456.98)

Вектор ознак [6]: (1, 22, 163, 476, 2612)
Довірчий інтервал [6]: (386.61, 457.85)

Вектор ознак [7]: (1, 20, 180, 471, 2815)
Довірчий інтервал [7]: (387.14, 468.51)

Вектор ознак [8]: (1, 17, 140, 523, 2527)
Довірчий інтервал [8]: (362.95, 431.55)

Вектор ознак [9]: (1, 21, 92, 483, 2720)
Довірчий інтервал [9]: (364.91, 424.81)

Вектор ознак [10]: (1, 18, 173, 542, 2817)
Довірчий інтервал [10]: (389.24, 474.64)

Вектор ознак [11]: (1, 22, 87, 501, 2736)
Довірчий інтервал [11]: (369.51, 434.49)

Вектор ознак [12]: (1, 20, 93, 471, 2682)
Довірчий інтервал [12]: (355.16, 417.79)

В

Коефіцієнт множинної кореляції

In [142]:
y_b = np.mean(Y)
print(y_b)

408.875


In [143]:
num = B @ X @ Y - n * y_b**2
denom = Y.T @ Y - n * y_b**2
print(num)
print(denom)

6241.7308787880465
11245.75


In [144]:
R_2 = num / denom
print(R_2)

0.5550302006347329


In [145]:
R = np.sqrt(R_2)
print(R)

0.7450034903507049


In [146]:
print(model.rsquared)

0.5550302006454558


In [147]:
print(np.sqrt(model.rsquared))

0.7450034903579015
