In [86]:
import numpy as np
from scipy.stats import t
import statsmodels.api as sm

In [87]:
X_1 = np.array([22, 17, 18, 15, 24, 22, 20, 17, 21, 18, 22, 20, 17, 15, 21, 15])

X_2 = np.array([180, 154, 217, 170, 103, 163, 180, 140, 92, 173, 87, 93, 210, 110, 86, 175])

X_3 = np.array([518, 475, 510, 493, 516, 476, 471, 523, 483, 542, 501, 471, 523, 538, 472, 467])

X_4 = np.array([2801, 2543, 2573, 2648, 2643, 2612, 2815, 2527, 2720, 2817, 2736, 2682, 2593, 2627, 2532, 2693])

In [88]:
len(X_1)

16

In [89]:
X = np.array([X_1, X_2, X_3, X_4])
X = np.concatenate(X).reshape(4, 16)
X

array([[  22,   17,   18,   15,   24,   22,   20,   17,   21,   18,   22,
          20,   17,   15,   21,   15],
       [ 180,  154,  217,  170,  103,  163,  180,  140,   92,  173,   87,
          93,  210,  110,   86,  175],
       [ 518,  475,  510,  493,  516,  476,  471,  523,  483,  542,  501,
         471,  523,  538,  472,  467],
       [2801, 2543, 2573, 2648, 2643, 2612, 2815, 2527, 2720, 2817, 2736,
        2682, 2593, 2627, 2532, 2693]])

In [90]:
X.T

array([[  22,  180,  518, 2801],
       [  17,  154,  475, 2543],
       [  18,  217,  510, 2573],
       [  15,  170,  493, 2648],
       [  24,  103,  516, 2643],
       [  22,  163,  476, 2612],
       [  20,  180,  471, 2815],
       [  17,  140,  523, 2527],
       [  21,   92,  483, 2720],
       [  18,  173,  542, 2817],
       [  22,   87,  501, 2736],
       [  20,   93,  471, 2682],
       [  17,  210,  523, 2593],
       [  15,  110,  538, 2627],
       [  21,   86,  472, 2532],
       [  15,  175,  467, 2693]])

In [91]:
Y = np.array([452, 377, 478, 371, 397, 404, 427, 396, 399, 418, 413, 412, 423, 393, 381, 401])
Y

array([452, 377, 478, 371, 397, 404, 427, 396, 399, 418, 413, 412, 423,
       393, 381, 401])

Визначити статистичні оцінки для  параметрів лінійної множинної регресії

In [92]:
Z = np.linalg.inv(X @ X.T)
Z

array([[ 1.07674360e-02,  2.84829459e-04,  7.89307162e-05,
        -1.07295481e-04],
       [ 2.84829459e-04,  4.20553913e-05, -6.79884480e-06,
        -3.06531627e-06],
       [ 7.89307162e-05, -6.79884480e-06,  7.41917709e-05,
        -1.40841187e-05],
       [-1.07295481e-04, -3.06531627e-06, -1.40841187e-05,
         3.58047784e-06]])

In [93]:
X_Y = X @ Y
X_Y

array([  124541,   963527,  3265275, 17415854])

In [94]:
B = Z @ X_Y
B

array([4.51618072, 0.40925209, 0.24881935, 0.05235702])

In [95]:
eq_str = 'y = '

for i in range(len(B)):
    print(f'b{i} = {B[i]:.4f}')
    eq_str += f'{B[i]:.4f} '
    if i != 0:
        eq_str += f'* x_i{i} '
    if i+1 != len(B):
        eq_str += '+ '
    
print(eq_str)

b0 = 4.5162
b1 = 0.4093
b2 = 0.2488
b3 = 0.0524
y = 4.5162 + 0.4093 * x_i1 + 0.2488 * x_i2 + 0.0524 * x_i3 


Побудувати довірчий інтервал

In [96]:
y = 0.99
alpha = 1 - y
print(f'alpha = {alpha:.2f}')

alpha = 0.01


In [97]:
n = X.shape[1]
n

16

In [98]:
m = X.shape[0]
m

4

In [99]:
pred_Y = B @ X
pred_Y

array([448.56180268, 391.13300026, 431.71145062, 398.62490816,
       417.31170485, 421.25862668, 428.5679299 , 396.50908768,
       395.0818419 , 434.44169209, 402.86822296, 385.99951408,
       428.61229739, 384.16715639, 380.04619588, 396.55793147])

In [100]:
e = Y - pred_Y
e

array([  3.43819732, -14.13300026,  46.28854938, -27.62490816,
       -20.31170485, -17.25862668,  -1.5679299 ,  -0.50908768,
         3.9181581 , -16.44169209,  10.13177704,  26.00048592,
        -5.61229739,   8.83284361,   0.95380412,   4.44206853])

In [101]:
S_2 = np.sum(e**2) / (n-m)
print(S_2)

418.7491228721567


In [102]:
S = np.sqrt(S_2)
print(S)

20.463360498025654


In [103]:
t_val = t.ppf(1-alpha/2, df=n-m)
print(t_val)

3.0545395893929017


In [104]:
for i in range(Y.shape[0]):
    x_0 = X.T[i].reshape(-1, 1)
    y_0 = pred_Y[i]
    
    margin = t_val*S*np.sqrt((x_0.T @ Z @ x_0)[0][0])
    
    low = y_0 - margin
    high = y_0 + margin
    
    print(f'y[{i}]: [{low:.4f}, {high:.4f}]')

y[0]: [422.3996, 474.7240]
y[1]: [374.4146, 407.8514]
y[2]: [396.6377, 466.7852]
y[3]: [370.6203, 426.6296]
y[4]: [379.9360, 454.6874]
y[5]: [390.3551, 452.1621]
y[6]: [391.5503, 465.5856]
y[7]: [365.7534, 427.2648]
y[8]: [366.9887, 423.1749]
y[9]: [413.0034, 455.8800]
y[10]: [374.5837, 431.1528]
y[11]: [357.1670, 414.8320]
y[12]: [395.5395, 461.6851]
y[13]: [340.5925, 427.7418]
y[14]: [353.8862, 406.2062]
y[15]: [358.8162, 434.2996]


In [105]:
model = sm.OLS(Y.reshape(16,1), X.T).fit()

In [106]:
predictions = model.get_prediction(X.T)
conf_int = predictions.conf_int(alpha=alpha)

In [107]:
for i, (features, intervals) in enumerate(zip(X.T, conf_int), 1):
    feature = tuple(int(val) for val in features[1:])
    interval = tuple(round(float(val), 2) for val in intervals)
    
    print(f'Вектор ознак [{i}]: {feature}')
    print(f'Довірчий інтервал [{i}]: {interval}')
    print()

Вектор ознак [1]: (180, 518, 2801)
Довірчий інтервал [1]: (422.4, 474.72)

Вектор ознак [2]: (154, 475, 2543)
Довірчий інтервал [2]: (374.41, 407.85)

Вектор ознак [3]: (217, 510, 2573)
Довірчий інтервал [3]: (396.64, 466.79)

Вектор ознак [4]: (170, 493, 2648)
Довірчий інтервал [4]: (370.62, 426.63)

Вектор ознак [5]: (103, 516, 2643)
Довірчий інтервал [5]: (379.94, 454.69)

Вектор ознак [6]: (163, 476, 2612)
Довірчий інтервал [6]: (390.36, 452.16)

Вектор ознак [7]: (180, 471, 2815)
Довірчий інтервал [7]: (391.55, 465.59)

Вектор ознак [8]: (140, 523, 2527)
Довірчий інтервал [8]: (365.75, 427.26)

Вектор ознак [9]: (92, 483, 2720)
Довірчий інтервал [9]: (366.99, 423.17)

Вектор ознак [10]: (173, 542, 2817)
Довірчий інтервал [10]: (413.0, 455.88)

Вектор ознак [11]: (87, 501, 2736)
Довірчий інтервал [11]: (374.58, 431.15)

Вектор ознак [12]: (93, 471, 2682)
Довірчий інтервал [12]: (357.17, 414.83)

Вектор ознак [13]: (210, 523, 2593)
Довірчий інтервал [13]: (395.54, 461.69)

Вектор оз

Коефіцієнт множинної кореляції

In [108]:
y_b = np.mean(Y)
print(y_b)

408.875


In [109]:
num = B @ X @ Y - n * y_b**2
denom = Y.T @ Y - n * y_b**2
print(num)
print(denom)

6220.76052561868
11245.75


In [110]:
R_2 = num / denom
print(R_2)

0.5531654647861352


In [111]:
R = np.sqrt(R_2)
print(R)

0.7437509427127708


In [112]:
print(model.rsquared)

0.9981292661293092


In [113]:
print(np.sqrt(model.rsquared))

0.9990641951993421
