In [1]:
import numpy as np
import statsmodels.api as sm

МНОЖИННА НЕЛІНІЙНА РЕГРЕСІЯ

In [2]:
y = np.array([34.00, 30.61, 31.43, 27.58, 28.92, 27.45, 18.41, 26.25, 26.51, 23.06, 23.18, 22.51, 22.25, 21.64, 20.38])
x = np.array([1740, 1860, 1910, 2050, 2060, 2070, 2100, 2150, 2210, 2300, 2350, 2340, 2450, 2500, 2600])
z = np.array([420, 410, 390, 300, 320, 340, 350, 370, 410, 550, 530, 550, 490, 350, 330])

In [3]:
X = np.column_stack((np.ones_like(x), x, x**2, z, z**2))
X

array([[      1,    1740, 3027600,     420,  176400],
       [      1,    1860, 3459600,     410,  168100],
       [      1,    1910, 3648100,     390,  152100],
       [      1,    2050, 4202500,     300,   90000],
       [      1,    2060, 4243600,     320,  102400],
       [      1,    2070, 4284900,     340,  115600],
       [      1,    2100, 4410000,     350,  122500],
       [      1,    2150, 4622500,     370,  136900],
       [      1,    2210, 4884100,     410,  168100],
       [      1,    2300, 5290000,     550,  302500],
       [      1,    2350, 5522500,     530,  280900],
       [      1,    2340, 5475600,     550,  302500],
       [      1,    2450, 6002500,     490,  240100],
       [      1,    2500, 6250000,     350,  122500],
       [      1,    2600, 6760000,     330,  108900]])

In [4]:
Y = y.reshape(-1,1)
Y

array([[34.  ],
       [30.61],
       [31.43],
       [27.58],
       [28.92],
       [27.45],
       [18.41],
       [26.25],
       [26.51],
       [23.06],
       [23.18],
       [22.51],
       [22.25],
       [21.64],
       [20.38]])

Визначення статистичних оцінок для параметрів

In [5]:
Z = np.linalg.inv(X.T @ X)
Z

array([[ 7.62710337e+02, -5.24727379e-01,  1.17728824e-04,
        -9.00694457e-01,  1.05449716e-03],
       [-5.24727379e-01,  4.11406201e-04, -9.32057219e-08,
         3.75359696e-04, -4.45186760e-07],
       [ 1.17728824e-04, -9.32057219e-08,  2.11912224e-11,
        -8.10339490e-08,  9.59809347e-11],
       [-9.00694457e-01,  3.75359696e-04, -8.10339490e-08,
         2.28129645e-03, -2.64823413e-06],
       [ 1.05449716e-03, -4.45186760e-07,  9.59809347e-11,
        -2.64823413e-06,  3.08853705e-09]])

In [6]:
X_Y = X.T @ Y
X_Y

array([[3.84180000e+02],
       [8.24532100e+05],
       [1.79158225e+09],
       [1.55525100e+05],
       [6.53543470e+07]])

In [7]:
B = Z @ X_Y
B

array([[ 1.19739487e+02],
       [-7.48985349e-02],
       [ 1.37264339e-05],
       [ 1.35838834e-02],
       [-1.38737695e-05]])

In [8]:
print(f'y = {B[0]} + {B[1]} * x_i + {B[2]} * x^2_i + {B[3]} * z_i + {B[4]} * z^2_i')

y = [119.73948687] + [-0.07489853] * x_i + [1.37264339e-05] * x^2_i + [0.01358388] * z_i + [-1.38737695e-05] * z^2_i


Побудувати довірчий інтервал

In [9]:
alpha = 0.01

In [10]:
model = sm.OLS(Y, X).fit()

In [11]:
predictions = model.get_prediction(X)
conf_int = predictions.conf_int(alpha=alpha)

In [12]:
for i, (features, intervals) in enumerate(zip(X, conf_int), 1):
    feature = tuple(int(val) for val in features[1:])
    interval = tuple(round(float(val), 2) for val in intervals)

    print(f'Вектор ознак [{i}]: {feature}')
    print(f'Довірчий інтервал [{i}]: {interval}')
    print()

Вектор ознак [1]: (1740, 3027600, 420, 176400)
Довірчий інтервал [1]: (27.2, 41.26)

Вектор ознак [2]: (1860, 3459600, 410, 168100)
Довірчий інтервал [2]: (26.81, 35.5)

Вектор ознак [3]: (1910, 3648100, 390, 152100)
Довірчий інтервал [3]: (26.28, 33.61)

Вектор ознак [4]: (2050, 4202500, 300, 90000)
Довірчий інтервал [4]: (20.69, 32.73)

Вектор ознак [5]: (2060, 4243600, 320, 102400)
Довірчий інтервал [5]: (22.35, 30.9)

Вектор ознак [6]: (2070, 4284900, 340, 115600)
Довірчий інтервал [6]: (23.09, 29.97)

Вектор ознак [7]: (2100, 4410000, 350, 122500)
Довірчий інтервал [7]: (22.56, 29.52)

Вектор ознак [8]: (2150, 4622500, 370, 136900)
Довірчий інтервал [8]: (21.22, 29.35)

Вектор ознак [9]: (2210, 4884100, 410, 168100)
Довірчий інтервал [9]: (19.33, 29.66)

Вектор ознак [10]: (2300, 5290000, 550, 302500)
Довірчий інтервал [10]: (18.13, 28.59)

Вектор ознак [11]: (2350, 5522500, 530, 280900)
Довірчий інтервал [11]: (18.68, 26.98)

Вектор ознак [12]: (2340, 5475600, 550, 302500)
Довірч

Обчислити коефіцієнт множинної кореляції

In [13]:
print(model.rsquared)

0.735143348706146


In [14]:
print(np.sqrt(model.rsquared))

0.8574050085613834
